# Generated by Django 5.2.7 on 2025-10-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
