# Generated by Django 5.2.7 on 2025-10-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('quiz', '0001_initial'),
        ('score', '0002_alter_score_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='player.player'),
        ),
        migrations.AlterField(
            model_name='score',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='quiz.quiz'),
        ),
    ]
