# Generated by Django 5.2.7 on 2025-11-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_alter_score_player_alter_score_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='time_only_correct',
            field=models.IntegerField(default=0),
        ),
    ]
