# Generated by Django 5.2.7 on 2025-10-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_updated_at_alter_category_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
