# Generated by Django 5.2.7 on 2025-10-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_quiz'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='quiz',
        ),
        migrations.AddField(
            model_name='category',
            name='quizzes',
            field=models.ManyToManyField(related_name='categories', to='quiz.quiz'),
        ),
    ]
