# Generated by Django 5.2.7 on 2025-12-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_quiz_category_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='transparent',
            field=models.BooleanField(default=False),
        ),
    ]
