# Generated by Django 5.2.7 on 2025-10-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_image_question_transparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.IntegerField(default=10000),
        ),
    ]
