# Generated by Django 5.2.7 on 2025-10-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_question_points_alter_question_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
