# Generated by Django 5.2.7 on 2025-10-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_alter_answer_question'),
        ('question', '0003_alter_question_category_alter_question_quiz'),
        ('response', '0002_alter_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='answer.answer'),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='question.question'),
        ),
    ]
