# Generated by Django 5.2.7 on 2025-11-15 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_alter_answer_question'),
        ('response', '0003_alter_response_answer_alter_response_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='answer.answer'),
        ),
    ]
