# Generated by Django 5.2.7 on 2025-10-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_answer_updated_at_alter_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
